// <auto-generated />
namespace WiGi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDocIdToPages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDocIdToPages));
        
        string IMigrationMetadata.Id
        {
            get { return "201211230203131_AddDocIdToPages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
