// <auto-generated />
namespace WiGi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddAboutFieldToPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAboutFieldToPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201211260525197_AddAboutFieldToPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
